CREATE TABLE user_preference
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username              VARCHAR(255)                            NOT NULL,
    default_limit         INT,
    default_year_range    INT,
    favorite_assignees    VARCHAR(255),
    favorite_technologies VARCHAR(255),
    CONSTRAINT pk_user_preference PRIMARY KEY (id)
);

ALTER TABLE user_preference
    ADD CONSTRAINT uc_user_preference_username UNIQUE (username);