CREATE TABLE competitor_assignees
(
    competitor_id BIGINT NOT NULL,
    assignee_name VARCHAR(200)
);

CREATE TABLE competitors
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code         VARCHAR(50)                             NOT NULL,
    display_name VARCHAR(200)                            NOT NULL,
    active       BOOLEAN                                 NOT NULL,
    description  VARCHAR(500),
    industry     VARCHAR(100),
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_competitors PRIMARY KEY (id)
);

ALTER TABLE competitors
    ADD CONSTRAINT uc_competitors_code UNIQUE (code);

CREATE INDEX idx_assignee_name ON competitor_assignees (assignee_name);

CREATE INDEX idx_competitor_active ON competitors (active);

CREATE UNIQUE INDEX idx_competitor_code ON competitors (code);

ALTER TABLE competitor_assignees
    ADD CONSTRAINT fk_competitor_assignees_on_competitor FOREIGN KEY (competitor_id) REFERENCES competitors (id);
CREATE TABLE competitor_assignees
(
    competitor_id BIGINT NOT NULL,
    assignee_name VARCHAR(200)
);

CREATE TABLE competitors
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code         VARCHAR(50)                             NOT NULL,
    display_name VARCHAR(200)                            NOT NULL,
    active       BOOLEAN                                 NOT NULL,
    description  VARCHAR(500),
    industry     VARCHAR(100),
    jurisdiction VARCHAR(10)                             NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_competitors PRIMARY KEY (id)
);

ALTER TABLE competitors
    ADD CONSTRAINT uc_competitors_code UNIQUE (code);

CREATE INDEX idx_assignee_name ON competitor_assignees (assignee_name);

CREATE INDEX idx_competitor_active ON competitors (active);

CREATE UNIQUE INDEX idx_competitor_code ON competitors (code);

CREATE INDEX idx_competitor_jurisdiction ON competitors (jurisdiction);

ALTER TABLE competitor_assignees
    ADD CONSTRAINT fk_competitor_assignees_on_competitor FOREIGN KEY (competitor_id) REFERENCES competitors (id);