CREATE TABLE monitoring_asset
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    VARCHAR(255),
    ip_address VARCHAR(255),
    CONSTRAINT pk_monitoringasset PRIMARY KEY (id)
);