CREATE TABLE subscription
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    VARCHAR(255),
    plan_type  VARCHAR(255),
    start_date date,
    end_date   date,
    status     VARCHAR(255),
    CONSTRAINT pk_subscription PRIMARY KEY (id)
);