
drop table competitor_filings;

CREATE TABLE competitor_filings
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    competitor_id    BIGINT                                  NOT NULL,
    patent_id        VARCHAR(50)                             NOT NULL,
    title            VARCHAR(500)                            NOT NULL,
    publication_date date                                    NOT NULL,
    jurisdiction     VARCHAR(10),
    assignee         VARCHAR(200),
    fetched_at       TIMESTAMP                               NOT NULL,
    filing_type      VARCHAR(100),
    status           VARCHAR(20),
    CONSTRAINT pk_competitor_filings PRIMARY KEY (id)
);

ALTER TABLE competitor_filings
    ADD CONSTRAINT uc_competitor_filings_patentid UNIQUE (patent_id);

CREATE INDEX idx_competitor_id ON competitor_filings (competitor_id);



CREATE UNIQUE INDEX idx_patent_id ON competitor_filings (patent_id);

CREATE INDEX idx_pub_date ON competitor_filings (publication_date);
CREATE TABLE competitor_filings
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    competitor_id    BIGINT                                  NOT NULL,
    patent_id        VARCHAR(50)                             NOT NULL,
    title            VARCHAR(500)                            NOT NULL,
    publication_date date                                    NOT NULL,
    jurisdiction     VARCHAR(10),
    assignee         VARCHAR(200),
    fetched_at       TIMESTAMP                               NOT NULL,
    filing_type      VARCHAR(100),
    status           VARCHAR(20),
    CONSTRAINT pk_competitor_filings PRIMARY KEY (id)
);

ALTER TABLE competitor_filings
    ADD CONSTRAINT uc_competitor_filings_patentid UNIQUE (patent_id);

CREATE INDEX idx_competitor_id ON competitor_filings (competitor_id);

CREATE INDEX idx_competitor_pub_date ON competitor_filings (competitor_id, publication_date);

CREATE UNIQUE INDEX idx_patent_id ON competitor_filings (patent_id);

CREATE INDEX idx_pub_date ON competitor_filings (publication_date);
CREATE TABLE competitor_filings
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    competitor_id    BIGINT                                  NOT NULL,
    patent_id        VARCHAR(50)                             NOT NULL,
    title            VARCHAR(500)                            NOT NULL,
    publication_date date                                    NOT NULL,
    jurisdiction     VARCHAR(10),
    filed_by         VARCHAR(200),
    current_owner    VARCHAR(200),
    filing_type      VARCHAR(100),
    status           VARCHAR(20),
    fetched_at       TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_competitor_filings PRIMARY KEY (id)
);

ALTER TABLE competitor_filings
    ADD CONSTRAINT uc_competitor_filings_patentid UNIQUE (patent_id);

CREATE INDEX idx_competitor_id ON competitor_filings (competitor_id);

CREATE UNIQUE INDEX idx_patent_id ON competitor_filings (patent_id);