CREATE TABLE search_activity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     VARCHAR(255),
    search_mode VARCHAR(255),
    created_at  TIMESTAMP,
    CONSTRAINT pk_searchactivity PRIMARY KEY (id)
);