CREATE TABLE analytics_report
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    report_name  VARCHAR(255)                            NOT NULL,
    report_year  INT                                     NOT NULL,
    report_data  CLOB,
    generated_at TIMESTAMP,
    generated_by VARCHAR(255),
    CONSTRAINT pk_analytics_report PRIMARY KEY (id)
);