CREATE TABLE patent_citations
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    citing_patent_number VARCHAR(255)                            NOT NULL,
    cited_patent_number  VARCHAR(255)                            NOT NULL,
    cited_patent_title   VARCHAR(1000),
    cited_patent_date    date,
    citation_sequence    INT,
    citation_category    VARCHAR(255),
    citation_direction   VARCHAR(255),
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    citation_type        VARCHAR(255)                            NOT NULL,
    citation_country     VARCHAR(255),
    CONSTRAINT pk_patent_citations PRIMARY KEY (id)
);

CREATE INDEX idx_cited_patent ON patent_citations (cited_patent_number);

CREATE INDEX idx_citing_patent ON patent_citations (citing_patent_number);