CREATE TABLE blacklisted_tokens
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token          VARCHAR(500)                            NOT NULL,
    blacklisted_at TIMESTAMP                               NOT NULL,
    expires_at     TIMESTAMP                               NOT NULL,
    user_email     VARCHAR(255),
    CONSTRAINT pk_blacklisted_tokens PRIMARY KEY (id)
);

ALTER TABLE blacklisted_tokens
    ADD CONSTRAINT uc_blacklisted_tokens_token UNIQUE (token);

CREATE INDEX idx_expiry ON blacklisted_tokens (expires_at);

CREATE INDEX idx_token ON blacklisted_tokens (token);
CREATE TABLE blacklisted_tokens
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token          VARCHAR(500)                            NOT NULL,
    blacklisted_at TIMESTAMP                               NOT NULL,
    expires_at     TIMESTAMP                               NOT NULL,
    user_email     VARCHAR(255),
    CONSTRAINT pk_blacklisted_tokens PRIMARY KEY (id)
);

ALTER TABLE blacklisted_tokens
    ADD CONSTRAINT uc_blacklisted_tokens_token UNIQUE (token);

CREATE INDEX idx_expiry ON blacklisted_tokens (expires_at);

CREATE INDEX idx_token ON blacklisted_tokens (token);