CREATE TABLE monitoring_subscriptions
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                  VARCHAR(255)                            NOT NULL,
    tier                     VARCHAR(255)                            NOT NULL,
    type                     VARCHAR(255)                            NOT NULL,
    alert_frequency          VARCHAR(255)                            NOT NULL,
    status                   VARCHAR(255)                            NOT NULL,
    email_alerts_enabled     BOOLEAN,
    dashboard_alerts_enabled BOOLEAN,
    created_at               TIMESTAMP,
    CONSTRAINT pk_monitoring_subscriptions PRIMARY KEY (id)
);

ALTER TABLE monitoring_subscriptions
    ADD CONSTRAINT uk_active_subscription_per_config UNIQUE (user_id, type, tier, alert_frequency, email_alerts_enabled,
                                                             dashboard_alerts_enabled, status);