CREATE TABLE trademark_bookmarks
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       VARCHAR(255),
    trademark_id  VARCHAR(255),
    source        VARCHAR(255),
    bookmarked_at date,
    CONSTRAINT pk_trademark_bookmarks PRIMARY KEY (id)
);

ALTER TABLE trademark_bookmarks
    ADD CONSTRAINT uc_66547b6ead6669c99329975d5 UNIQUE (user_id, trademark_id);
CREATE TABLE trademark_bookmarks
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       VARCHAR(255),
    trademark_id  VARCHAR(255),
    source        VARCHAR(255),
    bookmarked_at date,
    CONSTRAINT pk_trademark_bookmarks PRIMARY KEY (id)
);

ALTER TABLE trademark_bookmarks
    ADD CONSTRAINT uc_66547b6ead6669c99329975d5 UNIQUE (user_id, trademark_id);