CREATE TABLE api_usage_log
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          VARCHAR(255),
    service          VARCHAR(255),
    action           VARCHAR(255),
    status           VARCHAR(255),
    response_time_ms BIGINT                                  NOT NULL,
    timestamp        TIMESTAMP,
    CONSTRAINT pk_api_usage_log PRIMARY KEY (id)
);